<span style=color:red;font-size:60px>ASSIGNMENT</span>

<span style=color:blue;font-size:50px>NUMPY BASIC</span>

<span style=color:green>Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.</span>

In [4]:
import numpy as np

# Given list
list_ = ['1', '2', '3', '4', '5']

# Create a NumPy array from the list
array_list = np.array(object=list_)
print(f"Data type of list_: {type(list_)}")
print(f"Data type of array_list: {type(array_list)}")


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


<span style=color:green>Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.</span>

Ans-

In [5]:
import numpy as np


list_ = ['1', '2', '3', '4', '5']

# Create a NumPy array from the list
array_list = np.array(object=list_)

# Print data type of each element in the list
print("Data type of each element in list:")
for element in list_:
    print(f"{element}: {type(element)}")

# Print data type of each element in the NumPy array
print("\nData type of each element in array_list:")
for element in array_list:
    print(f"{element}: {type(element)}")


Data type of each element in list:
1: <class 'str'>
2: <class 'str'>
3: <class 'str'>
4: <class 'str'>
5: <class 'str'>

Data type of each element in array_list:
1: <class 'numpy.str_'>
2: <class 'numpy.str_'>
3: <class 'numpy.str_'>
4: <class 'numpy.str_'>
5: <class 'numpy.str_'>


<span style=color:green>Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)</span>

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Ans-

In [4]:
import numpy as np
list_=['1','2','3','4','5']

arr_list=np.array(object=list_, dtype=int)

print("datatype of each element in list:")
for element in list_:
    print(f"{element}:{type(element)}")
    
# print the data type of each element in the modified numpy array
print("/nDatatype of each element in modified array list:")
for element in arr_list:
    print(f"{element}:{type(element)}")

datatype of each element in list:
1:<class 'str'>
2:<class 'str'>
3:<class 'str'>
4:<class 'str'>
5:<class 'str'>
/nDatatype of each element in modified array list:
1:<class 'numpy.int64'>
2:<class 'numpy.int64'>
3:<class 'numpy.int64'>
4:<class 'numpy.int64'>
5:<class 'numpy.int64'>


In [7]:
import numpy as np
num_list=[[1,2,3],[4,5,6]]
num_array=np.array(object=num_list)

print("\datatype of each element in array:")
for row in num_array:
    for element in row:
        
        print(f"{element}:{type(element)}")

\datatype of each element in array:
1:<class 'numpy.int64'>
2:<class 'numpy.int64'>
3:<class 'numpy.int64'>
4:<class 'numpy.int64'>
5:<class 'numpy.int64'>
6:<class 'numpy.int64'>


<span style=color:green>Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size</span>

In [20]:
import numpy as np
shape=np.shape(num_array)
size=np.size(num_array)

print(f"shape of array:{shape}")
print(f"size of array:{size}")

shape of array:(2, 3)
size of array:6


<span style=color:green>Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]</span>

Ans-

In [22]:
import numpy as np
zeros=np.zeros((3,3))

# print the result
print(f"3*3 matrix zeros:{zeros}")

3*3 matrix zeros:[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<span style=color:green>Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]</span>

Ans-

In [25]:
import numpy as np
ide_mat=np.eye(5)

print(f"5*5 identity matrix:{ide_mat}")

5*5 identity matrix:[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
